name: Construir Interfaces Base de Datos

on:
  push:
    branches:
      - main1

jobs: 
  construir:
    name: Construir Interfaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'             # cachea ~/.npm, NO node_modules

      - name: Instalar dependencias (limpio)
        run: npm ci

      - name: Ver versiones (debug)
        run: |
          node -v
          npx tsc -v || true
          npm ls typescript @types/node || true

      - name: Limpiar lib
        run: rm -rf lib

      - name: Crear Build
        run: npm run ci   # o tu comando real de build (p.ej. npm run build)

  creartag:
    name: Crear Tag
    needs: construir
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # para ver tags existentes

      - name: Obtener el último tag
        id: get_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "CoopeTypes1.0.0")
          echo "Última versión encontrada: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Generar nueva versión
        id: bump_version
        run: |
          latest_version="${LATEST_TAG//CoopeTypes/}"
          IFS='.' read -r -a version_parts <<< "$latest_version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_version="CoopeTypes$major.$minor.$new_patch"
          echo "Nueva versión: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Configurar credenciales de Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Borbon-Coope/db-types.git

      - name: Eliminar tag si ya existe
        run: |
          git fetch --tags
          if git rev-parse $NEW_VERSION >/dev/null 2>&1; then
            git push --delete origin $NEW_VERSION || true
            git tag -d $NEW_VERSION || true
          fi

      - name: Crear y subir nuevo tag
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
